name: Update Trending Products

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-trends:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Update trending products
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
          WEBSHARE_PROXY_USER: ${{ secrets.WEBSHARE_PROXY_USER }}
          WEBSHARE_PROXY_PASS: ${{ secrets.WEBSHARE_PROXY_PASS }}
          ETSY_API_KEY: ${{ secrets.ETSY_API_KEY }}
        run: npm run update-trends
        
      - name: Commit and push if changes exist
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add src/data/trending.ts
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update trending products" && git push)